version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  api:
    build: ./
    container_name: api_backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - PORT=5000
    volumes:
      - ./my-business-back:/src

volumes:
  data: {}
