version: '3.8'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_PASSWORD=${pg_password}
      - POSTGRES_DB=${pg_db}
      - POSTGRES_USER=${pg_user}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server/
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    container_name: api_backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - PORT=5000

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

  front:
    build:
      context: ./client/
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api
    ports:
      - '3000:3000'
