name: Node.js App Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x' # Change to your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build # Replace with your build script if needed

    - name: Copy application files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # Add your server's IP address or hostname as a GitHub secret
        username: ${{ secrets.SERVER_USERNAME }} # Add your server's SSH username as a GitHub secret
        key: ${{ secrets.SERVER_SSH_KEY }} # Add your server's SSH private key as a GitHub secret
        source: '.' # The path to your application files
        target: '/server/my-business-back/' # The path on the server where you want to deploy the app

    - name: SSH into the server and start the app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /server/my-business-back
          pm2 restart index
