name: Node.js App Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create .env file
      run: echo "PORT=3000" >> .env
           echo "HOST=http://localhost" >> .env
           echo "ALLOWED_ORIGIN=http://localhost:3000" >> .env
           echo "ACCESS_TOKEN_PRIVATE_KEY=${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}" >> .env
           echo "REFRESH_TOKEN_PRIVATE_KEY=${{ secrets.REFRESH_TOKEN_PRIVATE_KEY }}" >> .env
           echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x' # Change to your required Node.js version

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build the application
      run: npm run build
      
    - name: Copy .env file to the server
      run: sshpass -p ${{ secrets.SERVER_PASSWORD }} scp .env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/server/my-business-back/

    - name: Copy application files to server
      run: rsync -avz -e "sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/server/my-business-back/

    - name: SSH into the server and start the app
      run: sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd ~/server/my-business-back/ && pm2 restart index --update-env'
